### PR TITLE
(Starter) Add gridsome-starter-resume

### PR DESCRIPTION
**Pull request by LokeCarlsson**
A resume starter built with bootstrap/bootstrap-vue

### CODE REVIEW

**Comment by tomtev** [comment]
Could you before I merge fix the screenshot? The sidebar should go all the way down, and it should be square

**Comment by tomtev** [comment]
Also, the author image should be visible on mobile also.

**Comment by LokeCarlsson** [comment]
@tomtev Fixed the image, but I don't understand what you mean with the author image on mobile though 😄

**Comment by tomtev** [comment]
@LokeCarlsson Hi again, The author Image in the sidebar should be in the header on mobile, imo :) Now there is no profile image visible on mobile screens.

**Comment by LokeCarlsson** [comment]
@tomtev This is intentional based on the MIT theme I used for the starter! I also thought about this but didn't find a good way to fit the image, was too small to have it in the header. I wanted it to be visible as well, but decided to skip it. Do you have any good idea how place it without making it tiny?

**Pull request merged**
