### PR TITLE
:sparkles: documenting GitLab's Implicit Grant

### PR DESCRIPTION
**Pull request by clorichel**

### CODE REVIEW

**Comment by clorichel** [comment]
@tomtev anything refraining this to be on the docs?

**Comment by thetre97** [comment]
@clorichel Thanks for adding this, and sorry it hasn't got in yet - but think this may be a bit out of date, now that Netlify recommends against this flow? https://www.netlifycms.org/docs/gitlab-backend/#client-side-implicit-grant-gitlab

**Comment by clorichel** [comment]
Can't say as I'm not using Netlify anymore. You can safely assume this is outdated if you'd like too 🤓

**Comment by thetre97** [comment]
Thanks anyway! Appreciate the time.

**Pull request closed without merging**
