### PR TITLE
Add ilrock prismic starter

### PR DESCRIPTION
**Pull request by ilrock**
Hey folks!

I would like to share my starter to integrate Gridsome with Prismic.

Repo: https://github.com/ilrock/gridsome-starter-prismic
Demo: https://5e92fa4fc739c4000645f643--vibrant-pasteur-05a750.netlify.com/

### CODE REVIEW

**Comment by 12vanblart** [comment]
It looks like your `/about` page is broken?

**Comment by ilrock** [comment]
Sorry about that, @12vanblart. I switched the Netlify url and now it's good to go.

The Demo URL is: https://vibrant-pasteur-05a750.netlify.app

**Comment by ilrock** [comment]
Hey @12vanblart - let me know if the update works for you

**Comment by 12vanblart** [comment]
@ilrock Yes - the link is working 😄 

The core team just needs to review this at this point - it can take a while to get through PR's, so just need to be patient from here :)

**Comment by mtlynch** [comment]
Cool, thanks @ilrock!

**Pull request merged**
