### PR TITLE
feat: Netlify CMS integration guide

### PR DESCRIPTION
**Pull request by Larsklopstra**
An full guide on how to implement the Netlify CMS plugin with Github in Gridsome.

### CODE REVIEW

**Comment by tomtev** [comment]
Thank you for this :) Could you add .md to the file extension?

**Comment by Larsklopstra** [comment]
@tomtev Haha, oops. Added it now 😁

**Comment by tomtev** [comment]
Awesome :) Could you also add a link to it in src/data/doc-links.yaml ?  Add it under Guides for now. We might move to another place later.

**Comment by Larsklopstra** [comment]
🚀

**Comment by Larsklopstra** [comment]
@tomtev Ready to merge

**Comment by hjvedvik** [comment]
This looks good to me. Thanks! @tomtev is on vacation, but I think he can take a look pretty soon :)

**Comment by Larsklopstra** [comment]
Cheers

**Comment by bbugh** [comment]
Here's the link to the docs if anyone ends up here via search: https://gridsome.org/docs/guide-netlify-cms

**Pull request merged**
