### PR TITLE
update to metainfo docs

### PR DESCRIPTION
**Pull request by petethompson**
I hit a stumbling block trying to figure out how to access data and props to pass to metaInfo, so I added a section to docs/head.md for other users' convenience.

### CODE REVIEW

**Comment by tomtev** [comment]
Thanks :) Could you delete the yarn.lock file?

**Comment by petethompson** [comment]
Whoops. Deleted!

**Comment by hjvedvik** [comment]
@petethompson I think you can discard the changes in the Yarn lock file instead of deleting it :)

**Comment by petethompson** [comment]
@hjvedvik: Sorry for the confusion. I've added the yarn.lock file back, in it's previous state, and rebased against master. I'm not sure how those integrity hashes were added.

**Review by thetre97 — APPROVED** [review]

**Pull request merged**
