### PR TITLE
Simple tutorial on adding local YAML files

### PR DESCRIPTION
**Pull request by sergeyfilimonov**

### CODE REVIEW

**Comment by tomtev** [comment]
This is nice :) We should also above that write something about how to add YAML data to GraphQL data layer, because that page is all fetching data into GraphQL data layer. 

There are two ways to do it:
1) https://gridsome.org/plugins/@gridsome/transformer-yaml
2) https://gridsome.org/plugins/gridsome-source-static-meta

**Comment by sergeyfilimonov** [comment]
@tomtev just tried to use the method I described above with importing yaml file within a components — and it doesn't work. Does this mean the method works only with pages?

**Comment by sergeyfilimonov** [comment]
@tomtev please look into the new commit. If I got you right, this is how one can use data from a YAML file with GraphQL.

**Comment by tomtev** [comment]
Hi again, could you remove the part on the top? That page is all about adding data to GraphQL. You could move that to "client-side data" instead :)

**Comment by sergeyfilimonov** [comment]
@hjvedvik done :)

**Comment by mtlynch** [comment]
Apologies for letting this go stale. We had a more recent submission that I felt demonstrated this concept more simply (#491), so we took that version. I'm trying to stay more on top of these so that the backlog is too short for redundant submissions.

**Pull request closed without merging**
