### PR TITLE
starter/jada

### PR DESCRIPTION
**Pull request by naiyerasif**
A starter based on SASS, specifically tailored for blogging.

- **Demo**: https://gridsome-jada.netlify.com/
- **Repo**: https://github.com/Microflash/jada

### CODE REVIEW

**Comment by Microflash** [comment]
Hey @tomtev @12vanblart, Is there anything I can do to move this PR ahead?

**Comment by 12vanblart** [comment]
Hi @Microflash! 👋

I try my best to help review PR's to make life easier for the core team, but I'm not actually able to merge the PR's.

Especially when it comes to Starters, I'm not 100% sure what tomtev and the core team wants to see before merging it. The issue I sent on your repo was just something I noticed that could help make your site even better than it was already. 

I should have time to double check tomorrow that everything in this PR is linked up correctly, but there are a lot of PR's adding starters and only so much time for the core team to look through them! 

Cheers! 🍻

**Comment by Microflash** [comment]
@12vanblart Thanks for your effort. This is understandable that the core team will focus primarily on the framework. I'd love to eventually see some clarity on what is expected from a starter as the Gridsome moves toward 1.0.

**Comment by tomtev** [comment]
@Microflash Really sorry about the late reply! Could you check the conflicts and we'll deploy. Nice design btw!

**Comment by Microflash** [comment]
@tomtev I've resolved the conflicts. And, thanks for the appreciation!

**Comment by naiyerasif** [comment]
Closing as this change has grown pretty stale and going nowhere.

**Pull request closed without merging**
