### PR TITLE
Added rasul to contributors and new blog post

### PR DESCRIPTION
**Pull request by rasulkireev**

### CODE REVIEW

**Comment by hjvedvik** [comment]
Thanks for the blog post, @rasulkireev. But the recommended way to add scripts in Gridsome is to use [Vue Meta](https://vue-meta.nuxtjs.org/), which is included. You can, for example, add a script tag like this:
```html
<template>
  ...
</template>

<script>
export default {
  metaInfo: {
    script: [
      { src: 'https://hypothes.is/embed.js', body: true }
    ]
  }
}
</script>
```
Maybe the [Populating `<head>`](https://gridsome.org/docs/head/) page should be updated with more examples. For example, how to add scripts in a component.

**Comment by rasulkireev** [comment]
Thanks for the note! You are totally right. I don't know why I didn't think of that straight away. I'll correct the post.

**Comment by tomtev** [comment]
Hi @rasulkireev This is great! Is it possible to add this as a guide documentation instead of as a blog post?

**Comment by mtlynch** [comment]
Closing, as this PR appears to be stalled. 

@rasulkireev - Feel free to open a new PR submitting this content as a guide or reopen this one when it's been adjusted.

**Pull request closed without merging**
