### PR TITLE
Submit BLNK Starter

### PR DESCRIPTION
**Pull request by angiemvella**

### CODE REVIEW

**Comment by thetre97** [comment]
Thanks @angiemvella ! 

Would you be able to revert the changes to the lock file please? I can then merge this in.

**Comment by angiemvella** [comment]
Hi @thetre97! Can you please confirm I have reverted the yarn.lock? Sorry about this - pretty new to contributing ☺️

**Comment by thetre97** [comment]
You have, thanks 👍. And sorry, I should have mentioned before, but I don't think the image `gridsome-starter-blnk-1680x1680.jpg` is being used? Would you be able to remove that as well?

**Comment by angiemvella** [comment]
@thetre97 done ☺️

**Review by thetre97 — APPROVED** [review]

**Pull request merged**
