### PR TITLE
Update guide-search.md

### PR DESCRIPTION
**Pull request by cfjedimaster**
A quick answer for search. It's kinda meh, but quick. I can expand this with screen shots and a sample project too, but I'd also like to talk about a client-side local option like Lunr, and you may have seen my issues related to that. If you don't want a quick fix that's fine too, it took me all of 5 minutes to write. :)

### CODE REVIEW

**Comment by hjvedvik** [comment]
Thanks for the PR. The custom script will break in SSR. Would it be better to add the script tag through `metaInfo` instead?

**Comment by cfjedimaster** [comment]
I didn't even test as I assumed it was so simple, and for that I'm sorry! I'm about to end my day - tomorrow I'll do a proper test and make this better. I really, REALLY apologize for not doing the bare minimum.

**Comment by hjvedvik** [comment]
No problem :) Just paste the script in a `mounted` hook should work fine. But using `metaInfo` is probably a better approach.

**Comment by cfjedimaster** [comment]
I used created but I see how mounted would be better. For metaInfo though, Google doesn't provide a script src and instead ask for the block of JS as I shwoed there. So would mounted be the only option?

**Comment by hjvedvik** [comment]
I haven't tested the script but something like this should work:

```js
export default {
  metaInfo: {
    script: [
      { src: 'https://cse.google.com/cse.js?cx=123:456', async: true, defer: true }
    ]
  }
}
```

**Comment by cfjedimaster** [comment]
My concern with that version is that it feels a bit more farther away than what Google recommends you cut and paste. How about I show both?

**Comment by tomtev** [comment]
I will close this for now. We will have a default search functionality for Gridsome at some point + plugins for tools like Algolia.

**Pull request closed without merging**
