### PR TITLE
Added Simple TailwindCSS + Markdown Starter

### PR DESCRIPTION
**Pull request by knightspore**
I added a barebones starer using TailwindCSS & Markdown with a simple home page and blog feed page.

### CODE REVIEW

**Comment by tomtev** [comment]
Is there a preview url? :)

**Comment by knightspore** [comment]
There is indeed, here you go
https://gridsome-tailwind-markdown-starter.netlify.app/

It's also listed in the README.md of the starter repo :)

**Comment by tomtev** [comment]
Nice, could you add it to the starters.yaml file? as ` preview: https://gridsome-tailwind-markdown-starter.netlify.app/`

**Comment by knightspore** [comment]
@tomtev done! I also tried to resolve the new conflicts that popped up (starters.yaml and contributors.yaml)

**Review by tonyketcham — APPROVED** [review]

**Comment by knightspore** [comment]
@tonyketcham Fixed the conflict, you can merge now. Thanks!

**Review by thetre97 — APPROVED** [review]

**Pull request merged**
