### PR TITLE
Header&Navbar Changes

### PR DESCRIPTION
**Pull request by luklus**
1. Remove dropdown in header, it has the same content as menu: twitter, discord, blog.
2. Move Search to right, no menu collapse now.
3. Items in Navbar Menu changed to uppercased.
4. Header height set to 62px.
5. Add target="_blank" and rel="noopener noreferrer" to links in Navbar.

### CODE REVIEW

**Comment by tomtev** [comment]
Thanks! I agree we could remove the dropdown. 
I tried to make some improvements to the design. Does it look good to you? 
skjermbilde 2019-01-11 kl 13 50 24

**Comment by luklus** [comment]
Yes, looks great :)

BTW, I like Your project, I hope I can help you from time to time. :)

**Comment by tomtev** [comment]
Updated the PR a bit :)

**Comment by hjvedvik** [comment]
Looks good! Can you change double quotes to single quotes and remove the semicolons in `SearchForm.vue`? Haven't included eslint rules in this project yet but we try to follow the `standardjs.com` style guide :)

**Comment by luklus** [comment]
Ok, I will add separate rules for this, and Gridsome project.

**Comment by hjvedvik** [comment]
@luklus We only follow that guide in the JS code. HTML and CSS should still have double quotes. And  the JS code in `SearchForm.vue` went back to double quotes your latest commit :)

**Comment by luklus** [comment]
Ok, i set finally my code E=editor to single quotes, and no semicolons, only in JS.

**Comment by tomtev** [comment]
Could you try remove the auto line breaks for attributes your code editor did? For example all SVGs looks a bit weird now.

skjermbilde 2019-01-14 kl 21 12 40

**Comment by tomtev** [comment]
I fixed this by moving SVG icons into its own files. I will merge this now. Thanks for the help :)

**Pull request merged**
