### PR TITLE
gridsome-shopify-starter

### PR DESCRIPTION
**Pull request by jsappme**
PWA and optimized to reach the highest Google Lighthouse scores.

### CODE REVIEW

**Comment by 12vanblart** [comment]
This looks exactly the same as the existing [Shopify Starter](https://gridsome.org/starters/shopify-starter/). 

I would submit your changes to the repository you forked. Presenting 2 of the same starter to end users will lead to confusion and requiring legwork on their side to determine what the difference is.

**Comment by jsappme** [comment]
The look is similar but the code is too different to be part of the same
repo. I removed and optimized some code to make it super light in order to
reach high performance score on the Google Lighthouse. I am fine to change
the ui so they dont look so similar but I think there are room for more
than one shopify starter in the directory.

**Comment by jsappme** [comment]
this starter has been fully re-writted to look very different than the other Bulma shopify starter

**Comment by 12vanblart** [comment]
Splendid work - this will stand out much better when sitting next to the other starter! 🎉

**Comment by jsappme** [comment]
@12vanblart any idea when this PR will be merged?

**Comment by 12vanblart** [comment]
Whenever the core team with permission to merge gets to it.

**Pull request merged**
