### PR TITLE
Add dependency install step

### PR DESCRIPTION
**Pull request by msgeissler**
Installed project dependencies are required for `gridsome develop`
https://github.com/gridsome/gridsome/issues/280

### CODE REVIEW

**Comment by tomtev** [comment]
@msgeissler `gridsome create xx` should install all dependencies automatically. You should only need to run `npm install` if you're forking a project from GitHub etc.

**Comment by robaxelsen** [comment]
@msgeissler did you try if simply doing `npm install` solves your issue? See comment from @tomtev above :point_up:

**Comment by msgeissler** [comment]
@tomtev you are right. I was a bit too hasty I guess. I always delete the node_modules locally as I use Docker for building. Not sure what the problem with https://github.com/gridsome/gridsome/issues/280 was then.

Is it okay if I move the `npm install` bit to a new FAQ entry referencing the error message from https://github.com/gridsome/gridsome/issues/280? It can probably be removed again once / if https://github.com/gridsome/gridsome/issues/281 is implemented.

**Comment by tomtev** [comment]
Hi again, sorry for the late reply. You could add something to the Troubleshoot page maybe? 
https://gridsome.org/docs/troubleshooting

**Comment by msgeissler** [comment]
The functionality has already been added to https://github.com/gridsome/gridsome/commit/89d6aa365eb44cde258f361d704b1ad06dbba04f in the meanwhile, so this should not be an issue anymore. If anyone still wants this to be in the doc for older gridsome beta versions, please re-open the issue and I can add it to the troubleshooting-section.

**Pull request closed without merging**
