### PR TITLE
Add Briefly starter

### PR DESCRIPTION
**Pull request by cossssmin**

### CODE REVIEW

**Comment by tomtev** [comment]
Could you fix the conflict? :)

**Comment by tomtev** [comment]
Another feedback: Would it be better to have the article list text in "text-gray-500" instead of text-gray-400. It's a bit hard to read them.

**Comment by cossssmin** [comment]
Done. Regarding text, it's based on the colors of the design it was inspired from, so I'd rather keep it that way. It's a one-character change if anyone wants more contrast.

**Comment by 12vanblart** [comment]
Quick note regarding the gray text contrast: 

`.text-gray-500` is still not a strong enough contrast ratio to meet WCAG AA Standards.

**Pull request closed without merging**
