### PR TITLE
Add Kontent plaftorm

### PR DESCRIPTION
**Pull request by Simply007**
Since there is already a [source plugin for Kentico Kontent](https://gridsome.org/plugins/@meeg/gridsome-source-kentico-kontent) I would like to register this platform as a one to the website.

@ondrabus is already working on [the lumen starter port](https://twitter.com/ondrabus/status/1301505304618831872) on his streams :-)

### CODE REVIEW

**Comment by mtlynch** [comment]
Thanks for submitting, @Simply007!

Can you help me to understand the purpose of this PR? It seems like it just creates an empty stub on [this page](https://next.gridsome.org/starters/). Is that correct?

If that's the case, can we hold off until we have a Kontent starter submitted and we can add an entry to the platform list at that point?

**Comment by Simply007** [comment]
Hey @mtlynch, 

Yes you are correct. This pull request just creates a placeholder.

I thought it is OK to do that since there are 8 other empty platforms. My understanding was of the filter could contain a platform if the platform has at least the plugin. And Kontent  [has this source plugin](https://next.gridsome.org/plugins/@meeg/gridsome-source-kentico-kontent).

**Comment by Simply007** [comment]
> If that's the case, can we hold off until we have a Kontent starter submitted and we can add an entry to the platform list at that point?

I am OK to wait once the starter is submitted, or you could even close this issue and the new platform could be included altogether with the starter submission.

**Comment by mtlynch** [comment]
I'm not sure why the other stubs are there. Maybe we should clean those up, too, because they probably just create more confusion than benefit.

Yeah, let's close this out. Feel free to include these changes in your PR for the starter.

**Pull request closed without merging**
